language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
branches:
  only:
    - master
